In [ ]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [7]:
vector_age = np.array([20, 45, 3, 71, 36])
vector_age

array([20, 45,  3, 71, 36])

In [8]:
matrix_table = np.array([
    [183, 164, 95, 158, 190],
    vector_age
])

matrix_table

array([[183, 164,  95, 158, 190],
       [ 20,  45,   3,  71,  36]])

In [6]:
matrix_table

array([list([183, 164, 95, 158, 190]), array([20, 45,  3, 74])],
      dtype=object)

In [9]:
!wget 'https://drive.google.com/uc?id=14d4PWnRDoHw83zk8JKhHl7iZJjuxAng1' -O test_img.png

--2023-02-06 10:52:57--  https://drive.google.com/uc?id=14d4PWnRDoHw83zk8JKhHl7iZJjuxAng1
Resolving drive.google.com (drive.google.com)... 74.125.199.138, 74.125.199.139, 74.125.199.100, ...
Connecting to drive.google.com (drive.google.com)|74.125.199.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-00-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/tettj174pe6p8bbepjlopemn67te947b/1675680750000/14904333240138417226/*/14d4PWnRDoHw83zk8JKhHl7iZJjuxAng1?uuid=72d792b5-7d7a-46c1-8079-44324cc8b1b7 [following]
--2023-02-06 10:52:57--  https://doc-00-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/tettj174pe6p8bbepjlopemn67te947b/1675680750000/14904333240138417226/*/14d4PWnRDoHw83zk8JKhHl7iZJjuxAng1?uuid=72d792b5-7d7a-46c1-8079-44324cc8b1b7
Resolving doc-00-c0-docs.googleusercontent.com (doc-00-c0-docs.googleusercontent.com)... 74.125.142.132, 2607:f8b0:400e:c08::84
Connecting to doc-00

In [10]:
import cv2

img = cv2.imread('/content/test_img.png')

print(type(img))
img

<class 'numpy.ndarray'>


array([[[220, 225, 251],
        [221, 225, 251],
        [222, 226, 252],
        ...,
        [211, 218, 251],
        [211, 218, 251],
        [211, 219, 251]],

       [[219, 230, 249],
        [220, 231, 249],
        [222, 232, 250],
        ...,
        [219, 232, 252],
        [219, 232, 252],
        [218, 232, 252]],

       [[220, 234, 245],
        [219, 233, 245],
        [219, 233, 245],
        ...,
        [208, 229, 248],
        [210, 230, 249],
        [211, 231, 249]],

       ...,

       [[143, 143, 250],
        [136, 136, 249],
        [131, 128, 248],
        ...,
        [208, 225, 233],
        [199, 217, 230],
        [197, 216, 229]],

       [[149, 150, 251],
        [146, 146, 250],
        [145, 142, 250],
        ...,
        [208, 225, 233],
        [198, 215, 228],
        [195, 212, 224]],

       [[144, 148, 250],
        [143, 144, 250],
        [140, 137, 249],
        ...,
        [213, 228, 233],
        [205, 220, 228],
        [201, 214, 221]]

In [11]:
print(f'ndim of vector_age {vector_age.ndim}')
print(f'ndim of matrix_table {matrix_table.ndim}')
print(f'ndim of image {img.ndim}')

ndim of vector_age 1
ndim of matrix_table 2
ndim of image 3


In [12]:
print(vector_age)
vector_age.shape

[20 45  3 71 36]


(5,)

In [13]:
print(matrix_table)
matrix_table.size

[[183 164  95 158 190]
 [ 20  45   3  71  36]]


10

In [14]:
print(vector_age)
vector_age.dtype

[20 45  3 71 36]


dtype('int64')

In [15]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [17]:
np.empty((2,3))

array([[3.6161977e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.linspace(0, 1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.random.randint(0,10,5)

array([9, 4, 0, 5, 0])

In [23]:
!wget 'https://drive.google.com/uc?id=1TaS4DsUnUQuqB0UxCscptbEQ0JoFmUMQ' -O income_by_age.txt

--2023-02-06 11:32:58--  https://drive.google.com/uc?id=1TaS4DsUnUQuqB0UxCscptbEQ0JoFmUMQ
Resolving drive.google.com (drive.google.com)... 173.194.202.100, 173.194.202.102, 173.194.202.139, ...
Connecting to drive.google.com (drive.google.com)|173.194.202.100|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0c-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/q68r3vdfpd27pqup91alveprsg11r61u/1675683150000/14904333240138417226/*/1TaS4DsUnUQuqB0UxCscptbEQ0JoFmUMQ?uuid=98dbfe68-0174-44e1-b2a1-4b29606ea33a [following]
--2023-02-06 11:32:59--  https://doc-0c-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/q68r3vdfpd27pqup91alveprsg11r61u/1675683150000/14904333240138417226/*/1TaS4DsUnUQuqB0UxCscptbEQ0JoFmUMQ?uuid=98dbfe68-0174-44e1-b2a1-4b29606ea33a
Resolving doc-0c-c0-docs.googleusercontent.com (doc-0c-c0-docs.googleusercontent.com)... 74.125.142.132, 2607:f8b0:400e:c08::84
Connecting to do

In [26]:
data=np.loadtxt('income_by_age.txt')
data.shape

(100, 2)

In [27]:
data[0]

array([ 38., 741.])

In [28]:
data[:5]

array([[  38.,  741.],
       [  32.,  630.],
       [  52., 2730.],
       [  33.,  552.],
       [  35.,  409.]])

In [29]:
data[:,0]

array([38., 32., 52., 33., 35., 46., 28., 30., 36., 32., 26., 33., 32.,
       39., 23., 30., 43., 48., 24., 39., 28., 29., 28., 32., 41., 39.,
       35., 32., 35., 34., 40., 30., 34., 34., 34., 36., 36., 44., 34.,
       45., 32., 31., 35., 37., 36., 44., 42., 38., 32., 34., 44., 36.,
       25., 30., 30., 43., 34., 50., 39., 35., 31., 41., 33., 29., 38.,
       35., 43., 34., 14., 40., 21., 45., 47., 32., 26., 25., 41., 33.,
       30., 33., 49., 37., 40., 40., 42., 42., 30., 33., 29., 30., 42.,
       31., 34., 30., 30., 40., 31., 31., 38., 38.])

In [30]:
data[:,1]

array([ 741.,  630., 2730.,  552.,  409., 1882., 1209.,  891.,  487.,
        629., 1492.,  504.,  658.,  903., 1964., 1000., 1451., 2157.,
       1811.,  944., 1280., 1156., 1171.,  722., 1296., 1012.,  359.,
        663.,  303.,  405., 1093.,  931.,  306.,  401.,  352.,  549.,
        497., 1634.,  386., 1861.,  605.,  777.,  400.,  655.,  569.,
       1591., 1439.,  794.,  636.,  400., 1713.,  521., 1610.,  989.,
        877., 1452.,  407., 2560.,  956.,  424.,  735., 1272.,  540.,
       1124.,  868.,  312., 1489.,  373., 3159., 1089., 2177., 1838.,
       2121.,  727., 1464., 1697., 1172.,  502.,  898.,  543., 2388.,
        646., 1045., 1076., 1318., 1361., 1010.,  515., 1060., 1011.,
       1441.,  801.,  379.,  992.,  893., 1088.,  745.,  782.,  793.,
        800.])

In [31]:
data[:,0].min()

14.0

In [33]:
idx=data[:,0].argmin()

In [34]:
data[idx]

array([  14., 3159.])

In [35]:
two_percent=data[:,1]*2/100
two_percent

array([14.82, 12.6 , 54.6 , 11.04,  8.18, 37.64, 24.18, 17.82,  9.74,
       12.58, 29.84, 10.08, 13.16, 18.06, 39.28, 20.  , 29.02, 43.14,
       36.22, 18.88, 25.6 , 23.12, 23.42, 14.44, 25.92, 20.24,  7.18,
       13.26,  6.06,  8.1 , 21.86, 18.62,  6.12,  8.02,  7.04, 10.98,
        9.94, 32.68,  7.72, 37.22, 12.1 , 15.54,  8.  , 13.1 , 11.38,
       31.82, 28.78, 15.88, 12.72,  8.  , 34.26, 10.42, 32.2 , 19.78,
       17.54, 29.04,  8.14, 51.2 , 19.12,  8.48, 14.7 , 25.44, 10.8 ,
       22.48, 17.36,  6.24, 29.78,  7.46, 63.18, 21.78, 43.54, 36.76,
       42.42, 14.54, 29.28, 33.94, 23.44, 10.04, 17.96, 10.86, 47.76,
       12.92, 20.9 , 21.52, 26.36, 27.22, 20.2 , 10.3 , 21.2 , 20.22,
       28.82, 16.02,  7.58, 19.84, 17.86, 21.76, 14.9 , 15.64, 15.86,
       16.  ])

In [36]:
data.mean(axis=0)

array([  35.14, 1030.4 ])

In [37]:
np.random.seed(8)
a = np.random.randint(0, 10, size=(5, 2))
a

array([[3, 4],
       [1, 9],
       [5, 8],
       [3, 8],
       [0, 5]])

In [38]:
!wget 'https://drive.google.com/uc?id=1xf9gRjobn3x7oMxVH_7ryOlg86f8cbzI' -O num_purchases.txt

--2023-02-06 12:35:36--  https://drive.google.com/uc?id=1xf9gRjobn3x7oMxVH_7ryOlg86f8cbzI
Resolving drive.google.com (drive.google.com)... 173.194.202.138, 173.194.202.100, 173.194.202.113, ...
Connecting to drive.google.com (drive.google.com)|173.194.202.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-0k-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/lsnb6tlrb3k0juqtcif1s3ub4p4mfu0e/1675686900000/14904333240138417226/*/1xf9gRjobn3x7oMxVH_7ryOlg86f8cbzI?uuid=018e3947-b35c-4f68-bc59-4effa03fa9cc [following]
--2023-02-06 12:35:36--  https://doc-0k-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/lsnb6tlrb3k0juqtcif1s3ub4p4mfu0e/1675686900000/14904333240138417226/*/1xf9gRjobn3x7oMxVH_7ryOlg86f8cbzI?uuid=018e3947-b35c-4f68-bc59-4effa03fa9cc
Resolving doc-0k-c0-docs.googleusercontent.com (doc-0k-c0-docs.googleusercontent.com)... 74.125.142.132, 2607:f8b0:400e:c08::84
Connecting to do

In [39]:
purchases = np.loadtxt('num_purchases.txt')
purchases

array([ 2., 11.,  7.,  2.,  5.,  2.,  5.,  8.,  5.,  4.,  3.,  5.,  4.,
        4.,  2., 10.,  2.,  3.,  5.,  3.,  2.,  4.,  6.,  5.,  3.,  2.,
        9.,  2.,  5.,  2.,  4.,  4.,  6.,  7.,  5.,  5.,  2.,  7.,  4.,
        4.,  3.,  2.,  4.,  3.,  3.,  2.,  5.,  3.,  3.,  4.,  2.,  3.,
        5.,  9.,  8.,  7.,  9.,  2.,  2.,  5.,  3.,  5.,  8.,  3.,  3.,
        2.,  5.,  2.,  2.,  4.,  3.,  6.,  8.,  4.,  4.,  2.,  3.,  6.,
        5.,  3.,  3.,  6.,  2.,  3.,  2.,  2.,  9.,  3.,  4.,  3.,  7.,
        2.,  9.,  4.,  3., 10.,  3.,  4.,  4.,  8.])

In [40]:
purchases = purchases.reshape((-1, 1))
purchases.ndim

2

In [41]:
np.set_printoptions(suppress=True)

np.hstack([data, purchases])

array([[  38.,  741.,    2.],
       [  32.,  630.,   11.],
       [  52., 2730.,    7.],
       [  33.,  552.,    2.],
       [  35.,  409.,    5.],
       [  46., 1882.,    2.],
       [  28., 1209.,    5.],
       [  30.,  891.,    8.],
       [  36.,  487.,    5.],
       [  32.,  629.,    4.],
       [  26., 1492.,    3.],
       [  33.,  504.,    5.],
       [  32.,  658.,    4.],
       [  39.,  903.,    4.],
       [  23., 1964.,    2.],
       [  30., 1000.,   10.],
       [  43., 1451.,    2.],
       [  48., 2157.,    3.],
       [  24., 1811.,    5.],
       [  39.,  944.,    3.],
       [  28., 1280.,    2.],
       [  29., 1156.,    4.],
       [  28., 1171.,    6.],
       [  32.,  722.,    5.],
       [  41., 1296.,    3.],
       [  39., 1012.,    2.],
       [  35.,  359.,    9.],
       [  32.,  663.,    2.],
       [  35.,  303.,    5.],
       [  34.,  405.,    2.],
       [  40., 1093.,    4.],
       [  30.,  931.,    4.],
       [  34.,  306.,    6.],
       [  

In [42]:
a

array([[3, 4],
       [1, 9],
       [5, 8],
       [3, 8],
       [0, 5]])

In [43]:
np.random.seed(6)
b = np.random.randint(-10, 0, size=(2, 2))
b

array([[ -1,  -7],
       [ -6, -10]])

In [44]:
np.vstack([a, b])

array([[  3,   4],
       [  1,   9],
       [  5,   8],
       [  3,   8],
       [  0,   5],
       [ -1,  -7],
       [ -6, -10]])

In [46]:
a

array([[3, 4],
       [1, 9],
       [5, 8],
       [3, 8],
       [0, 5]])

In [47]:
np.random.seed(8)
c = np.random.randint(-10, 0, size=(5, 1))
c

array([[-7],
       [-6],
       [-9],
       [-1],
       [-5]])

In [48]:
np.hstack([a, c])

array([[ 3,  4, -7],
       [ 1,  9, -6],
       [ 5,  8, -9],
       [ 3,  8, -1],
       [ 0,  5, -5]])

In [49]:
data = np.column_stack([data, purchases])
data

array([[  38.,  741.,    2.],
       [  32.,  630.,   11.],
       [  52., 2730.,    7.],
       [  33.,  552.,    2.],
       [  35.,  409.,    5.],
       [  46., 1882.,    2.],
       [  28., 1209.,    5.],
       [  30.,  891.,    8.],
       [  36.,  487.,    5.],
       [  32.,  629.,    4.],
       [  26., 1492.,    3.],
       [  33.,  504.,    5.],
       [  32.,  658.,    4.],
       [  39.,  903.,    4.],
       [  23., 1964.,    2.],
       [  30., 1000.,   10.],
       [  43., 1451.,    2.],
       [  48., 2157.,    3.],
       [  24., 1811.,    5.],
       [  39.,  944.,    3.],
       [  28., 1280.,    2.],
       [  29., 1156.,    4.],
       [  28., 1171.,    6.],
       [  32.,  722.,    5.],
       [  41., 1296.,    3.],
       [  39., 1012.,    2.],
       [  35.,  359.,    9.],
       [  32.,  663.,    2.],
       [  35.,  303.,    5.],
       [  34.,  405.,    2.],
       [  40., 1093.,    4.],
       [  30.,  931.,    4.],
       [  34.,  306.,    6.],
       [  

In [51]:
condition=data[:,1]>1500
condition

array([False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False,  True, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False,  True, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True, False, False,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [52]:
higher_1500=data[condition]
higher_1500

array([[  52., 2730.,    7.],
       [  46., 1882.,    2.],
       [  23., 1964.,    2.],
       [  48., 2157.,    3.],
       [  24., 1811.,    5.],
       [  44., 1634.,    7.],
       [  45., 1861.,    4.],
       [  44., 1591.,    2.],
       [  44., 1713.,    2.],
       [  25., 1610.,    5.],
       [  50., 2560.,    2.],
       [  14., 3159.,    2.],
       [  21., 2177.,    3.],
       [  45., 1838.,    6.],
       [  47., 2121.,    8.],
       [  25., 1697.,    2.],
       [  49., 2388.,    3.]])

In [53]:
is_interesting = np.zeros(shape=(100))
is_interesting

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [54]:
data = np.column_stack([data, is_interesting])
data

array([[  38.,  741.,    2.,    0.],
       [  32.,  630.,   11.,    0.],
       [  52., 2730.,    7.,    0.],
       [  33.,  552.,    2.,    0.],
       [  35.,  409.,    5.,    0.],
       [  46., 1882.,    2.,    0.],
       [  28., 1209.,    5.,    0.],
       [  30.,  891.,    8.,    0.],
       [  36.,  487.,    5.,    0.],
       [  32.,  629.,    4.,    0.],
       [  26., 1492.,    3.,    0.],
       [  33.,  504.,    5.,    0.],
       [  32.,  658.,    4.,    0.],
       [  39.,  903.,    4.,    0.],
       [  23., 1964.,    2.,    0.],
       [  30., 1000.,   10.,    0.],
       [  43., 1451.,    2.,    0.],
       [  48., 2157.,    3.,    0.],
       [  24., 1811.,    5.,    0.],
       [  39.,  944.,    3.,    0.],
       [  28., 1280.,    2.,    0.],
       [  29., 1156.,    4.,    0.],
       [  28., 1171.,    6.,    0.],
       [  32.,  722.,    5.,    0.],
       [  41., 1296.,    3.,    0.],
       [  39., 1012.,    2.,    0.],
       [  35.,  359.,    9.,    0.],
 

In [55]:
data[condition, -1] = 1
data

array([[  38.,  741.,    2.,    0.],
       [  32.,  630.,   11.,    0.],
       [  52., 2730.,    7.,    1.],
       [  33.,  552.,    2.,    0.],
       [  35.,  409.,    5.,    0.],
       [  46., 1882.,    2.,    1.],
       [  28., 1209.,    5.,    0.],
       [  30.,  891.,    8.,    0.],
       [  36.,  487.,    5.,    0.],
       [  32.,  629.,    4.,    0.],
       [  26., 1492.,    3.,    0.],
       [  33.,  504.,    5.,    0.],
       [  32.,  658.,    4.,    0.],
       [  39.,  903.,    4.,    0.],
       [  23., 1964.,    2.,    1.],
       [  30., 1000.,   10.,    0.],
       [  43., 1451.,    2.,    0.],
       [  48., 2157.,    3.,    1.],
       [  24., 1811.,    5.,    1.],
       [  39.,  944.,    3.,    0.],
       [  28., 1280.,    2.,    0.],
       [  29., 1156.,    4.,    0.],
       [  28., 1171.,    6.,    0.],
       [  32.,  722.,    5.,    0.],
       [  41., 1296.,    3.,    0.],
       [  39., 1012.,    2.,    0.],
       [  35.,  359.,    9.,    0.],
 

In [56]:
np.savetxt('data.txt', data)